name: trump
favicon: null
layout_spectrum: 0.21992
typography_spectrum: 0.69969
title: 'TRUMP: When I am Your Leader'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#bdc5b0'
    - '#8f9883'
    - '#79826d'
    - '#43523b'
  brandStrength: 0.1168812750838697
  lightness: 0.5985909339506179
  saturation: 0.013491207733750343
  rhythmicContrast: 0.6471927193924785
purpose: []
